# Generated by Django 2.1.1 on 2018-12-29 00:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_auto_20181229_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 29, 0, 24, 52, 613942, tzinfo=utc)),
        ),
    ]
